data_config:
  train_labels_path:
  - /mnt/lustre/scratch/biologie/franciso/Humboldt_Thesis/labels/merged_correctedvalidation_and_originaltraining_HPC.slp
  val_labels_path: null
  validation_fraction: 0.1
  use_same_data_for_val: false
  test_file_path: null
  provider: LabelsReader
  user_instances_only: true
  data_pipeline_fw: torch_dataset
  cache_img_path: null
  use_existing_imgs: false
  delete_cache_imgs_after_training: true
  parallel_caching: true
  cache_workers: 0
  preprocessing:
    ensure_rgb: false
    ensure_grayscale: true
    max_height: 800
    max_width: 800
    scale: 0.5
    crop_size: null
    min_crop_size: 100
    crop_padding: null
  use_augmentations_train: true
  augmentation_config:
    intensity: null
    geometric:
      rotation_min: -15.0
      rotation_max: 15.0
      rotation_p: 1.0
      scale_min: 0.9
      scale_max: 1.1
      scale_p: 1.0
      translate_width: 0.0
      translate_height: 0.0
      translate_p: null
      affine_p: 0.0
      erase_scale_min: 0.0001
      erase_scale_max: 0.01
      erase_ratio_min: 1.0
      erase_ratio_max: 1.0
      erase_p: 0.0
      mixup_lambda_min: 0.01
      mixup_lambda_max: 0.05
      mixup_p: 0.0
  use_negative_frames: false
  negative_loss_weight: 1.0
  skeletons:
  - nodes:
    - name: nose
    - name: left_ear
    - name: right_ear
    - name: torso_centre
    - name: tail_base
    edges:
    - source:
        name: torso_centre
      destination:
        name: nose
    - source:
        name: torso_centre
      destination:
        name: tail_base
    - source:
        name: nose
      destination:
        name: left_ear
    - source:
        name: nose
      destination:
        name: right_ear
    symmetries: []
    name: null
model_config:
  init_weights: default
  pretrained_backbone_weights: null
  pretrained_head_weights: null
  backbone_config:
    unet:
      in_channels: 1
      kernel_size: 3
      filters: 32
      filters_rate: 1.5
      max_stride: 16
      stem_stride: null
      middle_block: true
      up_interpolate: true
      stacks: 1
      convs_per_block: 2
      output_stride: 2
    convnext: null
    swint: null
  head_configs:
    single_instance: null
    centroid:
      confmaps:
        anchor_part: null
        sigma: 5.0
        output_stride: 2
    centered_instance: null
    bottomup: null
    multi_class_bottomup: null
    multi_class_topdown: null
  total_params: 1295081
trainer_config:
  train_data_loader:
    batch_size: 8
    num_workers: 0
    shuffle: true
  val_data_loader:
    batch_size: 8
    num_workers: 0
    shuffle: false
  model_ckpt:
    save_top_k: 1
    save_last: true
  trainer_devices: auto
  trainer_device_indices: null
  trainer_accelerator: auto
  profiler: null
  trainer_strategy: auto
  enable_progress_bar: true
  min_train_steps_per_epoch: 200
  train_steps_per_epoch: 200
  visualize_preds_during_training: true
  keep_viz: false
  max_epochs: 200
  seed: 42
  use_wandb: false
  save_ckpt: true
  ckpt_dir: /lustre/biologie/franciso/Humboldt_Thesis/models/topdown_v2/centroid
  run_name: topdown_v2_centroid
  resume_ckpt_path: null
  wandb:
    entity: null
    project: null
    name: topdown_v1_centroid
    save_viz_imgs_wandb: false
    api_key: null
    wandb_mode: null
    prv_runid: null
    group: null
    current_run_id: null
    viz_enabled: true
    viz_boxes: false
    viz_masks: false
    viz_box_size: 5.0
    viz_confmap_threshold: 0.1
    log_viz_table: false
    delete_local_logs: null
  optimizer_name: Adam
  optimizer:
    lr: 0.0001
    amsgrad: false
  lr_scheduler:
    step_lr: null
    reduce_lr_on_plateau:
      threshold: 1.0e-06
      threshold_mode: abs
      cooldown: 3
      patience: 5
      factor: 0.5
      min_lr: 1.0e-08
    cosine_annealing_warmup: null
    linear_warmup_linear_decay: null
  early_stopping:
    min_delta: 1.0e-06
    patience: 5
    stop_training_on_plateau: true
  online_hard_keypoint_mining:
    online_mining: false
    hard_to_easy_ratio: 2.0
    min_hard_keypoints: 2
    max_hard_keypoints: null
    loss_scale: 5.0
  zmq:
    controller_port: null
    controller_polling_timeout: 10
    publish_port: null
  eval:
    enabled: false
    frequency: 1
    oks_stddev: 0.025
    oks_scale: null
    match_threshold: 50.0
name: ''
description: ''
sleap_nn_version: 0.2.0
filename: ''
