#!/usr/bin/env python3
"""
Stage 08: Map RFID tag identifiers to biological mouse identities.

This script reads the cleaned RFID event table generated by Stage 07 and
adds a mouse_id column using an external CSV mapping file.

Example
-------
python scripts/08_map_rfid_tags.py \
    outputs/development_v1/rfid/26.07.15spareRFID_rfid_events.csv \
    config/rfid_tag_mapping_development.csv \
    --output-dir outputs/development_v1/rfid
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd


LOGGER = logging.getLogger("rfid_tag_mapping")


def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Map RFID tag IDs to biological mouse IDs."
    )

    parser.add_argument(
        "events_csv",
        type=Path,
        help="Clean RFID event CSV generated by Stage 07.",
    )

    parser.add_argument(
        "mapping_csv",
        type=Path,
        help="CSV containing mouse_id and rfid_tag columns.",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs/development_v1/rfid"),
        help="Directory for Stage 08 outputs.",
    )

    return parser.parse_args()


def normalise_tag_ids(series: pd.Series) -> pd.Series:
    """Standardise RFID tag IDs for reliable matching."""
    return (
        series.astype("string")
        .str.strip()
        .str.upper()
    )


def read_events(path: Path) -> pd.DataFrame:
    """Read and validate the cleaned Stage 07 event table."""
    if not path.exists():
        raise FileNotFoundError(f"RFID event file not found: {path}")

    events = pd.read_csv(
        path,
        dtype={
            "tag_id": "string",
            "reader": "string",
        },
        parse_dates=["timestamp"],
    )

    required_columns = {
        "timestamp",
        "tag_id",
        "reader",
    }

    missing = required_columns.difference(events.columns)

    if missing:
        raise ValueError(
            "Event file is missing required columns: "
            + ", ".join(sorted(missing))
        )

    events["tag_id"] = normalise_tag_ids(events["tag_id"])

    return events


def read_mapping(path: Path) -> pd.DataFrame:
    """Read and validate the RFID tag-to-mouse mapping table."""
    if not path.exists():
        raise FileNotFoundError(f"Mapping file not found: {path}")

    mapping = pd.read_csv(
        path,
        dtype={
            "mouse_id": "string",
            "rfid_tag": "string",
        },
    )

    required_columns = {
        "mouse_id",
        "rfid_tag",
    }

    missing = required_columns.difference(mapping.columns)

    if missing:
        raise ValueError(
            "Mapping file is missing required columns: "
            + ", ".join(sorted(missing))
        )

    mapping["mouse_id"] = (
        mapping["mouse_id"]
        .astype("string")
        .str.strip()
    )

    mapping["rfid_tag"] = normalise_tag_ids(mapping["rfid_tag"])

    if mapping["mouse_id"].isna().any():
        raise ValueError("Mapping file contains missing mouse IDs.")

    if mapping["rfid_tag"].isna().any():
        raise ValueError("Mapping file contains missing RFID tag IDs.")

    if mapping["mouse_id"].duplicated().any():
        duplicates = (
            mapping.loc[
                mapping["mouse_id"].duplicated(keep=False),
                "mouse_id",
            ]
            .unique()
            .tolist()
        )

        raise ValueError(
            "Mouse IDs occur more than once in the mapping file: "
            + ", ".join(duplicates)
        )

    if mapping["rfid_tag"].duplicated().any():
        duplicates = (
            mapping.loc[
                mapping["rfid_tag"].duplicated(keep=False),
                "rfid_tag",
            ]
            .unique()
            .tolist()
        )

        raise ValueError(
            "RFID tags occur more than once in the mapping file: "
            + ", ".join(duplicates)
        )

    return mapping


def map_mouse_ids(
    events: pd.DataFrame,
    mapping: pd.DataFrame,
) -> pd.DataFrame:
    """Add mouse IDs to RFID events using the mapping table."""
    mapped = events.merge(
        mapping,
        how="left",
        left_on="tag_id",
        right_on="rfid_tag",
        validate="many_to_one",
    )

    unknown_mask = mapped["mouse_id"].isna()

    if unknown_mask.any():
        unknown_tags = sorted(
            mapped.loc[unknown_mask, "tag_id"]
            .dropna()
            .unique()
            .tolist()
        )

        raise ValueError(
            "RFID events contain tags absent from the mapping file: "
            + ", ".join(unknown_tags)
        )

    mapped = mapped.drop(columns=["rfid_tag"])

    preferred_columns = [
        "raw_row_number",
        "timestamp",
        "seconds_from_rfid_start",
        "mouse_id",
        "tag_id",
        "reader",
        "duration_ms",
        "rfid_records",
    ]

    existing_preferred = [
        column
        for column in preferred_columns
        if column in mapped.columns
    ]

    remaining_columns = [
        column
        for column in mapped.columns
        if column not in existing_preferred
    ]

    return mapped[existing_preferred + remaining_columns]


def validate_output(
    events: pd.DataFrame,
    mapped: pd.DataFrame,
) -> None:
    """Validate the completed mapping output."""
    if len(events) != len(mapped):
        raise ValueError(
            "Row-count mismatch after mapping: "
            f"{len(events)} input rows versus {len(mapped)} output rows."
        )

    if mapped["mouse_id"].isna().any():
        raise ValueError("At least one RFID event has no mouse ID.")

    tag_to_mouse_counts = (
        mapped.groupby("tag_id")["mouse_id"]
        .nunique()
    )

    if (tag_to_mouse_counts != 1).any():
        raise ValueError(
            "At least one RFID tag maps to multiple mouse IDs."
        )


def write_summary(
    path: Path,
    events_path: Path,
    mapping_path: Path,
    mapped: pd.DataFrame,
) -> None:
    """Write a Stage 08 quality-control summary."""
    counts = (
        mapped.groupby(["mouse_id", "tag_id"])
        .size()
        .reset_index(name="event_count")
        .sort_values("mouse_id")
    )

    lines = [
        "RFID TAG-TO-MOUSE MAPPING SUMMARY",
        "=" * 70,
        "",
        f"Input events: {events_path}",
        f"Mapping file: {mapping_path}",
        "",
        f"Mapped event rows: {len(mapped):,}",
        f"Unique RFID tags: {mapped['tag_id'].nunique()}",
        f"Unique mouse IDs: {mapped['mouse_id'].nunique()}",
        f"Unmapped event rows: {mapped['mouse_id'].isna().sum():,}",
        "",
        "MAPPING COUNTS",
    ]

    for row in counts.itertuples(index=False):
        lines.append(
            f"Mouse {row.mouse_id} | "
            f"Tag {row.tag_id} | "
            f"{row.event_count:,} events"
        )

    lines.extend(
        [
            "",
            "VALIDATION",
            "Input and output row counts match",
            "Every RFID event has a mouse ID",
            "Each RFID tag maps to exactly one mouse",
            "",
        ]
    )

    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    """Run Stage 08."""
    args = parse_arguments()

    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    LOGGER.info("Reading RFID events: %s", args.events_csv)
    events = read_events(args.events_csv)

    LOGGER.info("Reading RFID mapping: %s", args.mapping_csv)
    mapping = read_mapping(args.mapping_csv)

    mapped = map_mouse_ids(events, mapping)
    validate_output(events, mapped)

    args.output_dir.mkdir(parents=True, exist_ok=True)

    input_stem = args.events_csv.stem.replace(
        "_rfid_events",
        "",
    )

    output_path = (
        args.output_dir
        / f"{input_stem}_rfid_events_mapped.csv"
    )

    summary_path = (
        args.output_dir
        / f"{input_stem}_rfid_mapping_summary.txt"
    )

    mapped.to_csv(
        output_path,
        index=False,
        date_format="%Y-%m-%d %H:%M:%S.%f",
    )

    write_summary(
        summary_path,
        args.events_csv,
        args.mapping_csv,
        mapped,
    )

    LOGGER.info("Input rows: %d", len(events))
    LOGGER.info("Mapped rows: %d", len(mapped))
    LOGGER.info(
        "Mapped mouse IDs: %s",
        ", ".join(sorted(mapped["mouse_id"].unique())),
    )
    LOGGER.info("Saved mapped events: %s", output_path)
    LOGGER.info("Saved summary: %s", summary_path)
    LOGGER.info("Stage 08 completed successfully.")


if __name__ == "__main__":
    main()
